name: Run Tests

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v2
      - name : Setup Node
        uses : actions/setup-node@v2
        with : 
          node-version: 18
      - name : install dependecies
        run : npm ci
      - name : Run Tests 
        run : npm run test 
          
  
